### Perform one-hot encoding manually by implementing a custom encoding function that dynamically adapts to new unseen categories in future data.

In [3]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [4]:
df = pd.read_csv("heart.csv")
df.head()

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,target
0,63,1,3,145,233,1,0,150,0,2.3,0,0,1,1
1,37,1,2,130,250,0,1,187,0,3.5,0,0,2,1
2,41,0,1,130,204,0,0,172,0,1.4,2,0,2,1
3,56,1,1,120,236,0,1,178,0,0.8,2,0,2,1
4,57,0,0,120,354,0,1,163,1,0.6,2,0,2,1

In [5]:
categorical_columns = [
    "sex",
    "cp",
    "fbs",
    "restecg",
    "exang",
    "slope",
    "ca",
    "thal"
]

print("Categorical columns:")
print(categorical_columns)

Categorical columns:
['sex', 'cp', 'fbs', 'restecg', 'exang', 'slope', 'ca', 'thal']

In [7]:
def manual_one_hot_encode(data, columns):

    result = data.copy()

    for column in columns:

        categories = []

        for value in result[column]:

            if value not in categories:
                categories.append(value)

        print("\nColumn:", column)
        print("Categories:", categories)

        for category in categories:

            new_column = column + "_" + str(category)

            result[new_column] = 0

            for index in result.index:

                if result.loc[index, column] == category:
                    result.loc[index, new_column] = 1

        result.drop(column, axis=1, inplace=True)

    return result

In [8]:
df_encoded = manual_one_hot_encode(
    df,
    categorical_columns
)

Column: sex
Categories: [1, 0]

Column: cp
Categories: [3, 2, 1, 0]

Column: fbs
Categories: [1, 0]

Column: restecg
Categories: [0, 1, 2]

Column: exang
Categories: [0, 1]

Column: slope
Categories: [0, 2, 1]

Column: ca
Categories: [0, 2, 1, 3, 4]

Column: thal
Categories: [1, 2, 3, 0]

In [9]:
print("Original Shape:", df.shape)

print("Encoded Shape:", df_encoded.shape)

display(df_encoded.head())

Original Shape: (303, 14)
Encoded Shape: (303, 31)

,age,trestbps,chol,thalach,oldpeak,target,sex_1,sex_0,cp_3,cp_2,...,slope_1,ca_0,ca_2,ca_1,ca_3,ca_4,thal_1,thal_2,thal_3,thal_0
0,63,145,233,150,2.3,1,1,0,1,0,...,0,1,0,0,0,0,1,0,0,0
1,37,130,250,187,3.5,1,1,0,0,1,...,0,1,0,0,0,0,0,1,0,0
2,41,130,204,172,1.4,1,0,1,0,0,...,0,1,0,0,0,0,0,1,0,0
3,56,120,236,178,0.8,1,1,0,0,0,...,0,1,0,0,0,0,0,1,0,0
4,57,120,354,163,0.6,1,0,1,0,0,...,0,1,0,0,0,0,0,1,0,0